### ISSUE TITLE
Actions don't work with explicit plug-ins

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#254]
Actions paired to InstancePlugin throws an AssertionError.

``` bash
# Traceback (most recent call last):
#   File "P:\pipeline\dev\git\pyblish-win\lib\pyblish\modules\pyblish-rpc\pyblish_rpc\service.py", line 119, in _dispatch
#     return func(*params)
#   File "P:\pipeline\dev\git\pyblish-win\lib\pyblish\modules\pyblish-rpc\pyblish_rpc\service.py", line 97, in process
#     action=action)
#   File "P:\pipeline\dev\git\pyblish-win\lib\pyblish\modules\pyblish-base\pyblish\plugin.py", line 414, in process
#     return __explicit_process(plugin, context, instance, action)
#   File "P:\pipeline\dev\git\pyblish-win\lib\pyblish\modules\pyblish-base\pyblish\plugin.py", line 430, in __explicit_process
#     "Cannot process an InstancePlugin without an instance. This is a bug")
# AssertionError: Cannot process an InstancePlugin without an instance. This is a bug
```

The error lies in a logic check made here:
- [https://github.com/pyblish/pyblish-base/blob/master/pyblish/plugin.py](https://github.com/pyblish/pyblish-base/blob/feb38302051201575e62a16851fbf94db90c75c9/pyblish/plugin.py#L429)

Which is logically making sure that, if a plug-in is an InstancePlugin but there is no instance being passed, the caller of this function is doing something wrong. But what it doesn't to take into account, is if there is an Action being processed, there doesn't have to be an instance.

Thanks to @madoodia and @BigRoy for spotting this.

**Comment by mottosso** [comment]
To reproduce:

``` python
import pyblish.api
import pyblish.plugin

class MyAction(pyblish.api.Action):
    def process(self, plugin, context):
        assert False, "Action ran"

class MyValidator(pyblish.api.InstancePlugin):
    order = pyblish.api.ValidatorOrder

    actions = [
        pyblish.api.Category("Scene"),
        MyAction,
    ]

context = pyblish.api.Context()
result = pyblish.plugin.process(MyValidator, context, instance=None, action="MyAction")
assert str(result["error"]) == "Action ran"
```
