### ISSUE TITLE
Incompatibility with pyblish-qml

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#308]
1.4.3 causes issues with pyblish-qml.

```bash
$ python -m pyblish_qml --debug
Starting Pyblish..
Starting in debug-mode
Looking for server..
 Listening on 127.0.0.1:9090
No existing server found, creating..
Debug server created successfully.
Running mocked RPC server @ 127.0.0.1:6000
Settings:
Listening on 127.0.0.1:6000  WindowTitle = Pyblish (DEBUG)

  ContextLabel = World
  WindowSize = (430, 600)
Entering state: "hidden"
Entering state: "ready"
Entering state: "clean"
Entering state: "alive"
Awaited statemachine for 7.00 ms
Entering state: "visible"
Entering state: "initialising"
Spent 1218.00 ms creating the application
Traceback (most recent call last):
  File "c:\pyblish-qml\pyblish_qml\control.py", line 809, in on_next
    self.item_model.update_with_result(result)
  File "c:\pyblish-qml\pyblish_qml\models.py", line 432, in update_with_result
    id = (result[type] or {}).get("id")
TypeError: sequence index must be integer, not 'str'
```

Somehow the result dictionary sometimes returns a plug-in, as opposed to a dictonary of results.

**Comment by mottosso** [comment]
This was an issue in pyblish-qml, not here.

https://github.com/pyblish/pyblish-qml/issues/216
