### ISSUE TITLE
module.__init__() argument 1 must be string, not unicode

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-base#310]
**Description**

Module discovery does not accept unicode.

**Short reproducible**
```
$ pyblish --add-plugin-path "C:\Users\tje\Desktop"
Traceback (most recent call last):
  File "C:\Users\tje\Documents\conda-git-deployment\windows\miniconda\envs\tgbvfx-environment\Scripts\pyblish-script.py", line 11, in <module>
    load_entry_point('pyblish-base', 'console_scripts', 'pyblish')()
  File "c:\users\tje\documents\conda-git-deployment\repositories\tgbvfx-environment\pyblish-base\pyblish\vendor\click\core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\tje\documents\conda-git-deployment\repositories\tgbvfx-environment\pyblish-base\pyblish\vendor\click\core.py", line 474, in main
    self.invoke(ctx)
  File "c:\users\tje\documents\conda-git-deployment\repositories\tgbvfx-environment\pyblish-base\pyblish\vendor\click\core.py", line 758, in invoke
    return self.invoke_subcommand(ctx, cmd, cmd_name, ctx.args[1:])
  File "c:\users\tje\documents\conda-git-deployment\repositories\tgbvfx-environment\pyblish-base\pyblish\vendor\click\core.py", line 764, in invoke_subcommand
    Command.invoke(self, ctx)
  File "c:\users\tje\documents\conda-git-deployment\repositories\tgbvfx-environment\pyblish-base\pyblish\vendor\click\core.py", line 659, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "c:\users\tje\documents\conda-git-deployment\repositories\tgbvfx-environment\pyblish-base\pyblish\vendor\click\core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "c:\users\tje\documents\conda-git-deployment\repositories\tgbvfx-environment\pyblish-base\pyblish\cli.py", line 222, in main
    available_plugins = api.discover(paths=plugin_paths)
  File "c:\users\tje\documents\conda-git-deployment\repositories\tgbvfx-environment\pyblish-base\pyblish\plugin.py", line 1263, in discover
    module = types.ModuleType(mod_name)
TypeError: module.__init__() argument 1 must be string, not unicode
```

**Suggested solution**
Force unicodes to strings:
```python
module = types.ModuleType(str(mod_name))
```

**Comment by mottosso** [comment]
I can't reproduce this. :(

```bash
$ pip install pyblish-base
$ pyblish --add-plugin-path "C:\Users\tje\Desktop"
$
```

**Comment by mottosso** [comment]
I think this might not be related to the path, but to the filename. What files are there inside of the folder you are testing with?

**Comment by tokejepsen** [comment]
Maybe you are right. Can't reproduce with the original reproducible, so definitely something about the files on my desktop.
If it too cumbersome to make the test pass with python 3, then I'll just leave it.
